//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _9._11._22_British_Time__model_first_entity_framework_
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Model1Container : DbContext
    {
        public Model1Container()
            : base("name=Model1Container")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Teachers> TeachersSet { get; set; }
        public virtual DbSet<Students> StudentsSet { get; set; }
        public virtual DbSet<Staffs> StaffsSet { get; set; }
        public virtual DbSet<Lessons> LessonsSet { get; set; }
    }
}
