//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _9._11._22_British_Time__model_first_entity_framework_
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staffs
    {
        public int StaffNo { get; set; }
        public string StaffName { get; set; }
        public string StaffMail { get; set; }
        public string StaffPassword { get; set; }
        public int StaffPhone { get; set; }
    }
}
